# Generated by Django 4.2.11 on 2024-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marnie',
            field=models.BooleanField(default=False),
        ),
    ]
