# Generated by Django 4.2.11 on 2024-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_marnie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an Agent.', verbose_name='User is an Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_marnie',
            field=models.BooleanField(default=False, help_text='Designates whether this user is Marnie Ferreira.', verbose_name='User is Marnie'),
        ),
    ]
