services:
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: manies_maintenance_manager_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme  # ✅ Removed unnecessary /var/www/metasophia mount
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-files.rule=Host(`metasophia.ar-ciel.org`)"
      - "traefik.http.routers.static-files.entrypoints=web"
      - "traefik.http.middlewares.static-headers.headers.accesscontrolalloworigin=*"

  static-files:
    image: nginx:latest
    container_name: static-files
    volumes:
      - /var/www/metasophia:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-files.rule=Host(`metasophia.ar-ciel.org`)"
      - "traefik.http.routers.static-files.entrypoints=web"
      - "traefik.http.services.static-files.loadbalancer.server.port=80"
      - "traefik.http.middlewares.static-headers.headers.accesscontrolalloworigin=*"
