# Generated by Django 4.2.13 on 2024-06-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_accepted_or_rejected_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="accepted_or_rejected",
            field=models.CharField(
                blank=True,
                choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                default="",
                max_length=8,
            ),
        ),
    ]
