# Generated by Django 4.2.13 on 2024-06-18 22:52

import django.core.validators
from django.db import migrations, models
import manies_maintenance_manager.jobs.validators
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_job_deposit_proof_of_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deposit_proof_of_payment",
            field=models.FileField(
                blank=True,
                help_text="Upload the deposit proof of payment here.",
                null=True,
                upload_to="deposit_pops/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    manies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
                verbose_name="Deposit Proof of Payment",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("pending_inspection", "Pending Inspection"),
                    ("inspection_completed", "Inspection Completed"),
                    ("quote_rejected_by_agent", "Quote Rejected By Agent"),
                    ("quote_accepted_by_agent", "Quote Accepted By Agent"),
                    ("deposit_pop_uploaded", "Deposit POP Uploaded"),
                ],
                default="pending_inspection",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
