# Generated by Django 4.2.13 on 2024-06-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_job_deposit_proof_of_payment_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the job was completed.",
                null=True,
                verbose_name="Job Date",
            ),
        ),
    ]
