# Generated by Django 4.2.13 on 2024-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_job_job_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Add any comments you have about the job here.",
                verbose_name="Comments",
            ),
        ),
    ]
