# Generated by Django 4.2.13 on 2024-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="Has the job been completed?",
                verbose_name="Job Complete",
            ),
        ),
    ]
