# Generated by Django 5.0.7 on 2024-08-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_rename_job_date_job_job_onsite_work_completion_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="complete",
        ),
    ]
