# Generated by Django 4.2.11 on 2024-05-05 18:48

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('address_details', models.TextField()),
                ('gps_link', models.URLField()),
                ('quote_request_details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
