# Generated by Django 4.2.13 on 2024-05-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import marnies_maintenance_manager.jobs.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField(editable=False)),
                ("date", models.DateField()),
                ("address_details", models.TextField()),
                ("gps_link", models.URLField()),
                ("quote_request_details", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            marnies_maintenance_manager.jobs.models.validate_user_is_agent
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "unique_together": {("agent", "number")},
            },
        ),
    ]
