# Generated by Django 4.2.13 on 2024-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="date_of_inspection",
            field=models.DateField(blank=True, null=True),
        ),
    ]
