# Generated by Django 4.2.13 on 2024-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_date_of_inspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="quote",
            field=models.FileField(blank=True, null=True, upload_to="quotes/"),
        ),
    ]
