# Generated by Django 4.2.11 on 2024-05-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import marnies_maintenance_manager.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_alter_job_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="agent",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[
                    marnies_maintenance_manager.jobs.models._validate_user_is_agent
                ],
            ),
        ),
    ]
