# Generated by Django 4.2.13 on 2024-05-26 12:26

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("pending_inspection", "Pending Inspection"),
                    ("inspection_completed", "Inspection Completed"),
                ],
                default="pending_inspection",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
