# Generated by Django 4.2.13 on 2024-06-01 13:58

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="accepted_or_rejected",
            field=models.CharField(
                blank=True,
                choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("pending_inspection", "Pending Inspection"),
                    ("inspection_completed", "Inspection Completed"),
                    ("quote_rejected_by_agent", "Quote Rejected By Agent"),
                ],
                default="pending_inspection",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
