# Generated by Django 4.2.13 on 2024-06-07 08:54

import django.core.validators
from django.db import migrations, models
import marnies_maintenance_manager.jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_job_accepted_or_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deposit_proof_of_payment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="deposit_pops/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    marnies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
            ),
        ),
    ]
