# Generated by Django 4.2.13 on 2024-06-21 15:18

import django.core.validators
from django.db import migrations, models
import marnies_maintenance_manager.jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="invoice",
            field=models.FileField(
                blank=True,
                help_text="Upload the invoice here.",
                null=True,
                upload_to="invoices/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    marnies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
                verbose_name="Invoice",
            ),
        ),
    ]
