# Generated by Django 4.2.13 on 2024-06-21 18:24

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_job_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("pending_inspection", "Pending Inspection"),
                    ("inspection_completed", "Inspection Completed"),
                    ("quote_rejected_by_agent", "Quote Rejected By Agent"),
                    ("quote_accepted_by_agent", "Quote Accepted By Agent"),
                    ("deposit_pop_uploaded", "Deposit POP Uploaded"),
                    ("marnie_completed", "Marnie has completed the job"),
                ],
                default="pending_inspection",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
