# Generated by Django 4.2.14 on 2024-07-25 10:23

import django.core.validators
from django.db import migrations
import marnies_maintenance_manager.jobs.validators
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_job_final_payment_pop_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deposit_proof_of_payment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Upload the deposit proof of payment here.",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="deposit_pops/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    marnies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
                verbose_name="Deposit Proof of Payment",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="final_payment_pop",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Upload the final payment proof of payment here.",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="final_payment_pops/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    marnies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
                verbose_name="Final Payment Proof of Payment",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="invoice",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Upload the invoice here.",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="invoices/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    marnies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="quote",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="quotes/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    marnies_maintenance_manager.jobs.validators.validate_pdf_contents,
                ],
            ),
        ),
    ]
