# Generated by Django 5.0.7 on 2024-08-02 21:11

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_jobcompletionphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("pending_inspection", "Pending Inspection"),
                    ("inspection_completed", "Inspection Completed"),
                    ("quote_uploaded", "Quote Uploaded"),
                    ("quote_rejected_by_agent", "Quote Rejected By Agent"),
                    ("quote_accepted_by_agent", "Quote Accepted By Agent"),
                    ("deposit_pop_uploaded", "Deposit POP Uploaded"),
                    ("marnie_completed", "Marnie has completed the job"),
                    (
                        "final_payment_pop_uploaded",
                        "Agent uploaded the final payment POP",
                    ),
                ],
                default="pending_inspection",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
