---
- name: Initial setup for new droplet
  hosts: new_{{ deploy_env }}_droplet
  become: true
  gather_facts: false
  vars:
    username: david
  vars_files:
    - .secrets/vault.yml

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: true

    - name: Allow user to sudo without password
      ansible.builtin.copy:
        content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ username }}"
        owner: root
        group: root
        mode: '0440'

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Read SSH public key from local machine
      slurp:
        src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
      register: ssh_key_file
      delegate_to: localhost
      become: false

    - name: Set SSH key variable
      set_fact:
        ssh_key: "{{ ssh_key_file['content'] | b64decode }}"

    - name: Add authorized key
      ansible.builtin.copy:
        content: "{{ ssh_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
