# Generated by Django 5.0.8 on 2024-08-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_is_marnie_user_is_manie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_manie",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is Manie Ferreira.",
                verbose_name="User is Manie",
            ),
        ),
    ]
